version: "3"

services:
  app:
    container_name: pipedrive_sync_service
    environment:
      - PIPEDRIVE_API_KEY=${PIPEDRIVE_API_KEY}
    build:
      context: ./Go
      dockerfile: pipedrive-sync/Dockerfile
    restart: "no"
